# Twitter users to watch
twitter:
  users:
    - fifacom

# Telegram bot secret token (https://core.telegram.org/bots)
telegram:
  bot_token: DDDDDDDDDD:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# in seconds
check_every: 120
